---
# tasks file for ansible-role-matomo

- name: Configure the Web server
  import_tasks: configure-web-server.yml
  when: matomo_configure_web_server | bool

- name: Get an HTTPS certificate
  import_tasks: get-https-certificate.yml

- name: Configure the application
  import_tasks: configure-application.yml

- name: Create the application's database
  import_tasks: create-database.yml

- name: Install the Debian package
  import_tasks: install-debian-package.yml

- name: Add additional functionality to the basic Matomo
  import_tasks: add-extras.yml
